### PR TITLE
Publication refactor

### PR DESCRIPTION
**Pull request by rjawesome**
https://github.com/biothings/biothings_explorer/issues/677. Handles different types of publications. For URLs, if it starts with the URL string of a prefix, it is turned into a curie by stripping the URL part and then adding the prefix.

For publication strings with CURIE prefixes, it is checked if the prefix [with ":" so like "PMID:"] exists (in any casing), and if so, strip the prefix. Then just add the prefix back on the beginning of the string.

Current info that is being used for the prefixes:
- {prop: "ref_pmid", prefix: "PMID:", urls: ["http://www.ncbi.nlm.nih.gov/pubmed/", "http://europepmc.org/abstract/MED/"]},
- {prop: "ref_pmcid", prefix: "PMCID:", urls: ["http://www.ncbi.nlm.nih.gov/pmc/articles/", "http://europepmc.org/articles/"]},
- {prop: "ref_clinicaltrials", prefix: "clinicaltrials:", urls: ["https://clinicaltrials.gov/ct2/show/"]},
- {prop: "ref_doi", prefix: "doi:", urls: ["https://doi.org/", "http://www.nejm.org/doi/full/", "https://www.tandfonline.com/doi/abs/", "http://onlinelibrary.wiley.com/doi/"]},
- {prop: "ref_isbn", prefix: "isbn:", urls: ["https://www.isbn-international.org/identifier/"]}

### CODE REVIEW

**Comment by colleenXu** [comment]
Hmmm, we are producing the desired behavior for PFOCR (mix of PMCID CURIEs for articles and urls for figures). But I'm a little concerned by:
* the figure urls start with the https version of what we currently check and turn into a CURIE: `https://www.ncbi.nlm.nih.gov/pmc/articles/`
* which makes me wonder...if we tried to cover http + https cases in the future (and turn them into CURIEs), would we introduce a bug with handling these figure urls...

Example of what BTE currently generates for PFOCR, which is what I wanted...:

```
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2577715/bin/fig-15.jpg",
                                "PMCID:PMC2577715",
                                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1994616/bin/JCI0731809.f2.jpg",
                                "PMCID:PMC1994616",
                                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3218933/bin/bcr2876-2.jpg",
                                "PMCID:PMC3218933",
                                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3669657/bin/nihms461261f6.jpg",
                                "PMCID:PMC3669657",
                                "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5962346/bin/nihms923919f1.jpg",
                                "PMCID:PMC5962346"
                            ],
                            "value_type_id": "linkml:Uriorcurie"
                        }
```

**Comment by colleenXu** [comment]
@rjawesome 

For clinicaltrials, can you add this base url? `https://www.clinicaltrials.gov/ct2/show/` In my test query for `Test for ref_doi, ref_clinicaltrials (and ref_pmid and ref_url)`, I'm see that this url is equivalent to `clinicaltrials:NCT02390947`, which is already present in that edge-attribute.

**Comment by colleenXu** [comment]
@rjawesome Also is it possible to do a quick-fix for CTD processing, to handle when the `data.PubMedIds` field returns pipe-delimited text? And put it into this feature for now? 

I know you handled it in the JQ-branches [here](https://github.com/biothings/biothings_explorer/issues/583#issue-1622873383)...but I'm not confident this will get in, in time for the upcoming "freeze".

**Comment by colleenXu** [comment]
Okay, done testing. Overall, it seems to be working well! 

To summarize my posts above:
* [the https PMC urls for PFOCR figure urls vs PharmGKB articles](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672377717): this may be tricky, and something we don't need to worry about yet because we haven't added PharmGKB to our config yet (and we likely won't until SRI Node Norm can support its ID-namespaces). 
* [Adding base urls to replace with prefix](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672588688). Just these are fine; remember that doing https for PMC ids will be problematic right now because of the point above
* [quick fix for CTD pmids](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672606874). a little out-of-scope, but would be nice to have a fix in for now...

**Comment by rjawesome** [comment]
> Also is it possible to do a quick-fix for CTD processing, to handle when the data.PubMedIds field returns pipe-delimited text? And put it into this feature for now?
From what I understand it's already handled. The CTD transformer converts pipe delimited to array, and the publication code is designed to handle an array if it is passed in. Let me know if there are any issues with this.

> Can you ADD some base urls for replacing with prefix?
Done.

> Hmmm, we are producing the desired behavior for PFOCR (mix of PMCID CURIEs for articles and urls for figures). But I'm a little concerned:
There's probably a few ways to go about this: 
1. I originally thought to look for "/" after the URL, but seems like doi ids contain these
2. look for image extensions and then exclude them
3. maybe write a regex/desired format for each ID and make sure the part after the URL matches

**Comment by colleenXu** [comment]
On [the https PMC urls for PFOCR figure urls vs PharmGKB articles](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672377717): 
* I imagine the "look for image extensions" or "regex" may be the solution. Regex in particular may also help with the clinicaltrials urls `https://clinicaltrials.gov/search?id=%22NCT00485888%22` which we currently don't replace with the CURIE (since the ID is between the two `%22` rather than at the end). 
    * However, I think this is some work for not much gain at the moment. It'll be more important later when we want to add PharmGKB to BTE's config list (noted in the PharmGKB issue [here](https://github.com/biothings/biothings_explorer/issues/556#issuecomment-1674111606))
    * So if you don't have the time to get this done today / tomorrow / early next week, I think it's okay to drop this topic until later...

**Comment by colleenXu** [comment]
I'll be retesting and looking more closely at what's going on with CTD right now...

**Comment by colleenXu** [comment]
On [Aadding base urls to replace with prefix](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672588688):

After retesting, this has been addressed! So the basic requirements of this feature have been met

**Comment by colleenXu** [comment]
On [quick fix for CTD pmids](https://github.com/biothings/api-respone-transform.js/pull/53#issuecomment-1672606874):
* this is definitely happening, see my examples below. It is happening with operations that have  `data.PubMedIds` fields and not `data.PubMedIDs` (used for other operations like the disease2chemical and disease2gene ones)
    * if you're trying to recreate the behavior, [remember to set up your smartapi overrides file](https://github.com/biothings/biothings_explorer/issues/677#issue-1821677954) 
* I would like this addressed if possible, before the code freeze. But if not, let me know and I can adjust x-bte annotation (remove the response-mappings for pmid fields). 

<details><summary>example query for operation chemical2gene</summary>

This [operation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/887ce3e5c966dc7e4a82e6ad920eb8c918f96b37/CTD/smartapi.yaml#L168) has the field spelled [data.PubMedIds](https://github.com/NCATS-Tangerine/translator-api-registry/blob/887ce3e5c966dc7e4a82e6ad920eb8c918f96b37/CTD/smartapi.yaml#L540) in its response. 

Send this query to CTD thru BTE:

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["MESH:C006303"],
                    "categories": ["biolink:SmallMolecule"]
                },
                "n1": {
                    "categories": ["biolink:Gene"]
                }
            }
        }
    }
}
```

The equivalent sub-query in BTE is the GET request http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303&inputTermSearchType=directAssociations&report=genes_curated&format=json

This part of the raw response is turned into the problematic edge in BTE:

```
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Bos taurus",
        "OrganismId": "9913",
        "PubMedIds": "15629191"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "Organism": "Mus musculus",
        "OrganismId": "10090",
        "PubMedIds": "15629191|19419996"
    },
    {
        "CasRN": "52583-41-2",
        "ChemicalId": "C006303",
        "ChemicalName": "acivicin",
        "GeneId": "2678",
        "GeneSymbol": "GGT1",
        "Input": "c006303",
        "PubMedIds": "1673268|1678558|19419996"
    }
```

The problematic edge with pipe-delimited strings  in the `biolink:publications` edge-attribute:

```
                "006f724ebdc9389dc3429ffb181e2150": {
                    "predicate": "biolink:related_to",
                    "subject": "PUBCHEM.COMPOUND:294641",
                    "object": "NCBIGene:2678",
                    "attributes": [
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:15629191",
                                "PMID:15629191|19419996",
                                "PMID:1673268|1678558|19419996"
                            ],
                            "value_type_id": "linkml:Uriorcurie"
                        }
                    ],
```

</details> 

<details><summary>example query for operation gene2chemical</summary>

This [operation](https://github.com/NCATS-Tangerine/translator-api-registry/blob/887ce3e5c966dc7e4a82e6ad920eb8c918f96b37/CTD/smartapi.yaml#L189) also has the field spelled [data.PubMedIds](https://github.com/NCATS-Tangerine/translator-api-registry/blob/887ce3e5c966dc7e4a82e6ad920eb8c918f96b37/CTD/smartapi.yaml#L546) in its response. 

Send this query to CTD thru BTE:

```
{
    "message": {
        "query_graph": {
            "edges": {
                "e01": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:related_to"]
                }
            },
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:10800"],
                    "categories": ["biolink:Gene"]
                },
                "n1": {
                    "categories": ["biolink:SmallMolecule"]
                }
            }
        }
    }
}
```

The equivalent sub-query in BTE is the GET request http://ctdbase.org/tools/batchQuery.go?inputType=chem&inputTerms=C006303&inputTermSearchType=directAssociations&report=genes_curated&format=json

BTE is creating responses like this, which are basically the pipe-delimited strings in the raw GET request's response with `PMID:` added to them

```
                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:16630147|17641958|18379861|19767084|20485159"
                            ],
                            "value_type_id": "linkml:Uriorcurie"
                        }

                        {
                            "attribute_type_id": "biolink:publications",
                            "value": [
                                "PMID:18651869|9797038",
                                "PMID:10825389|10851239|11093801|14718577|18651869",
                                "PMID:15888248"
                            ],
                            "value_type_id": "linkml:Uriorcurie"
                        }
```

</details>

**Comment by rjawesome** [comment]
Done.

**Pull request merged**
